### ISSUE TITLE
The colorization part didn't work well

### ISSUE THREAD

**Issue by Crinz** [tezignlab/subculture-colorization#4]
![ca](https://user-images.githubusercontent.com/50197299/131721731-0f9699b6-39fb-48f9-a2d4-9fbdd582fe12.JPG)

**Comment by zhuojg** [comment]
Hi.  
Did you download the checkpoint of colorization model as described in [this part](https://github.com/tezignlab/subculture-colorization#download-pre-trained-models) of README, and change the `config.ini` correctly?  

Firstly, you need to download all 4 files and move them to somewhere like `./ckpt`.
Then the `config.ini` should be like this:
```
[text2palette]
...

[colorization]
...

[streamlit]
text2palette_checkpoint_path = ./ckpt/ckpt-71
colorization_checkpoint_path = ./ckpt/ckpt-100
```

I tested the same colors as you generated, and it works just fine.
![image](https://user-images.githubusercontent.com/24386525/131774144-49baba94-b127-4aa4-8231-bebaf3a16967.png)

**Comment by Crinz** [comment]
Thanks for solving the problem. I accidentally add the file name extension 'index'. It works fine now.
